name: trigger jenkins job
on:
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.JENKINS_URL }}
        user: "wshah"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "foobar"
        wait: "true"
        timeout: "1000"
